// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCElvqD6SzVOlYii_TThaXoy8_XZT88Pkw',
    appId: '1:867477199658:web:ae5bebfbeb0940a68d1c53',
    messagingSenderId: '867477199658',
    projectId: 'rocis-todo',
    authDomain: 'rocis-todo.firebaseapp.com',
    storageBucket: 'rocis-todo.firebasestorage.app',
    measurementId: 'G-WBCJEY70B9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD5Dw_v-PeYj0qgsnQHG4wYw4VEbfLD9E',
    appId: '1:867477199658:android:966d4a50b5b02d4e8d1c53',
    messagingSenderId: '867477199658',
    projectId: 'rocis-todo',
    storageBucket: 'rocis-todo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANKSZvImO8-pWYu64E2KSYKVVtJ2ZL8VE',
    appId: '1:867477199658:ios:cab43f67930ee9d68d1c53',
    messagingSenderId: '867477199658',
    projectId: 'rocis-todo',
    storageBucket: 'rocis-todo.firebasestorage.app',
    iosClientId:
        '867477199658-f79j3ag3fj8dcpmmfpaljactnfcqvfov.apps.googleusercontent.com',
    iosBundleId: 'com.rocisapps.tasks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANKSZvImO8-pWYu64E2KSYKVVtJ2ZL8VE',
    appId: '1:867477199658:ios:cab43f67930ee9d68d1c53',
    messagingSenderId: '867477199658',
    projectId: 'rocis-todo',
    storageBucket: 'rocis-todo.firebasestorage.app',
    iosClientId:
        '867477199658-f79j3ag3fj8dcpmmfpaljactnfcqvfov.apps.googleusercontent.com',
    iosBundleId: 'com.rocisapps.tasks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCElvqD6SzVOlYii_TThaXoy8_XZT88Pkw',
    appId: '1:867477199658:web:e3b2c489e05117678d1c53',
    messagingSenderId: '867477199658',
    projectId: 'rocis-todo',
    authDomain: 'rocis-todo.firebaseapp.com',
    storageBucket: 'rocis-todo.firebasestorage.app',
    measurementId: 'G-PN6M22VEMQ',
  );
}
