// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REDACTED_WEB_API_KEY',
    appId: 'REDACTED_WEB_APP_ID',
    messagingSenderId: 'REDACTED_SENDER_ID',
    projectId: 'rocis-todo',
    authDomain: 'rocis-todo.firebaseapp.com',
    storageBucket: 'rocis-todo.firebasestorage.app',
    measurementId: 'G-WBCJEY70B9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REDACTED_ANDROID_API_KEY',
    appId: 'REDACTED_ANDROID_APP_ID',
    messagingSenderId: 'REDACTED_SENDER_ID',
    projectId: 'rocis-todo',
    storageBucket: 'rocis-todo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REDACTED_IOS_API_KEY',
    appId: 'REDACTED_IOS_APP_ID',
    messagingSenderId: 'REDACTED_SENDER_ID',
    projectId: 'rocis-todo',
    storageBucket: 'rocis-todo.firebasestorage.app',
    iosClientId:
        'REDACTED_IOS_CLIENT_ID',
    iosBundleId: 'com.rocisapps.tasks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REDACTED_IOS_API_KEY',
    appId: 'REDACTED_IOS_APP_ID',
    messagingSenderId: 'REDACTED_SENDER_ID',
    projectId: 'rocis-todo',
    storageBucket: 'rocis-todo.firebasestorage.app',
    iosClientId:
        'REDACTED_IOS_CLIENT_ID',
    iosBundleId: 'com.rocisapps.tasks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'REDACTED_WEB_API_KEY',
    appId: 'REDACTED_WINDOWS_APP_ID',
    messagingSenderId: 'REDACTED_SENDER_ID',
    projectId: 'rocis-todo',
    authDomain: 'rocis-todo.firebaseapp.com',
    storageBucket: 'rocis-todo.firebasestorage.app',
    measurementId: 'G-PN6M22VEMQ',
  );
}
