// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:rocis_tasks/features/categories/domain/models/category.dart';
import 'package:rocis_tasks/features/tasks/domain/models/sub_task.dart';
import 'package:rocis_tasks/features/tasks/domain/models/task.dart';
import 'package:rocis_tasks/features/tasks/domain/models/custom_field.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CategoryAdapter());
    registerAdapter(SubTaskAdapter());
    registerAdapter(TaskAdapter());
    registerAdapter(TaskPriorityAdapter());
    registerAdapter(CustomFieldTypeAdapter());
    registerAdapter(TaskCustomFieldAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CategoryAdapter());
    registerAdapter(SubTaskAdapter());
    registerAdapter(TaskAdapter());
    registerAdapter(TaskPriorityAdapter());
    registerAdapter(CustomFieldTypeAdapter());
    registerAdapter(TaskCustomFieldAdapter());
  }
}
